package ru.wisla.fm.processing.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import ru.wisla.fm.processing.domain.EventEntity;
import ru.wisla.fm.processing.persistence.EventRepository;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.UUID;

@Service
public class ThresholdService {

    private static final List<String> ACTIVE_STATUSES = List.of("new", "in_progress", "maintenance", "deferred");

    private final EventRepository eventRepository;

    public ThresholdService(EventRepository eventRepository) {
        this.eventRepository = eventRepository;
    }

    @Transactional
    public void evaluateAfterProcessing(EventEntity processedEvent, boolean thresholdEnabled) {
        if (!thresholdEnabled) {
            return;
        }
        evaluateAfterProcessing(processedEvent, 5, 10);
    }

    @Transactional
    public void evaluateAfterProcessing(EventEntity processedEvent, int count, int windowMin) {
        if (!"critical".equals(processedEvent.getSeverity())) {
            return;
        }
        Instant since = Instant.now().minus(windowMin, ChronoUnit.MINUTES);
        long criticalCount = countRecentCritical(processedEvent.getSourceId(), processedEvent.getCiId(), since);
        if (criticalCount < count) {
            return;
        }
        String syntheticTitle = syntheticTitle(count, windowMin);
        if (hasRecentSynthetic(processedEvent.getSourceId(), processedEvent.getCiId(), syntheticTitle, since)) {
            return;
        }
        createSyntheticEvent(processedEvent, count, windowMin, syntheticTitle);
    }

    private long countRecentCritical(UUID sourceId, UUID ciId, Instant since) {
        if (ciId == null) {
            return eventRepository.countBySourceIdAndCiIdIsNullAndSeverityAndCreatedAtAfterAndStatusIn(
                    sourceId, "critical", since, ACTIVE_STATUSES
            );
        }
        return eventRepository.countBySourceIdAndCiIdAndSeverityAndCreatedAtAfterAndStatusIn(
                sourceId, ciId, "critical", since, ACTIVE_STATUSES
        );
    }

    private boolean hasRecentSynthetic(UUID sourceId, UUID ciId, String title, Instant since) {
        if (ciId == null) {
            return eventRepository.existsBySourceIdAndCiIdIsNullAndTitleAndCreatedAtAfter(
                    sourceId, title, since
            );
        }
        return eventRepository.existsBySourceIdAndCiIdAndTitleAndCreatedAtAfter(
                sourceId, ciId, title, since
        );
    }

    private void createSyntheticEvent(EventEntity trigger, int count, int windowMin, String title) {
        EventEntity synthetic = new EventEntity();
        synthetic.setStatus("new");
        synthetic.setSeverity("fatal");
        synthetic.setTitle(title);
        synthetic.setDescription("Auto-generated by threshold rule after " + count
                + " critical events within " + windowMin + " minutes");
        synthetic.setSourceId(trigger.getSourceId());
        synthetic.setCiId(trigger.getCiId());
        synthetic.setNodeFqdn(trigger.getNodeFqdn());
        synthetic.setSystemName(trigger.getSystemName());
        synthetic.setSubsystemName(trigger.getSubsystemName());
        synthetic.setSourceAt(Instant.now());
        synthetic.setAttributes("{\"synthetic\":true,\"ruleType\":\"threshold\"}");
        eventRepository.save(synthetic);
    }

    private String syntheticTitle(int count, int windowMin) {
        return "Threshold: " + count + "+ critical events in " + windowMin + " minutes";
    }
}
