package ru.wisla.fm.processing.domain.service;

import ru.wisla.fm.processing.domain.Event;
import ru.wisla.fm.processing.domain.ThresholdPolicy;

import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Optional;
import java.util.UUID;

/**
 * The threshold rule, lifted out of {@code ThresholdService.evaluateAfterProcessing}. The two
 * counting queries stay behind {@link Window} so the short-circuit order is still decided here: the
 * existence check only runs once the count has breached, and reuses the same window start.
 *
 * <p>Only the literal severity {@code "critical"} qualifies — {@code "fatal"} is more severe but
 * does not trigger evaluation.
 */
public final class ThresholdEvaluator {

    /** The counting side of the rule; implemented over {@code EventStorePort}. */
    public interface Window {

        long countRecentCritical(UUID sourceId, UUID ciId, Instant since);

        boolean hasRecentSynthetic(UUID sourceId, UUID ciId, String title, Instant since);
    }

    /** Returns the synthetic roll-up event to save, or empty when the threshold does not fire. */
    public Optional<Event> evaluate(Event processedEvent, ThresholdPolicy policy, Instant now, Window window) {
        if (!"critical".equals(processedEvent.getSeverity())) {
            return Optional.empty();
        }
        Instant since = now.minus(policy.windowMin(), ChronoUnit.MINUTES);
        long criticalCount = window.countRecentCritical(
                processedEvent.getSourceId(), processedEvent.getCiId(), since);
        if (criticalCount < policy.count()) {
            return Optional.empty();
        }
        String syntheticTitle = syntheticTitle(policy);
        if (window.hasRecentSynthetic(
                processedEvent.getSourceId(), processedEvent.getCiId(), syntheticTitle, since)) {
            return Optional.empty();
        }
        return Optional.of(Event.synthetic(
                processedEvent, syntheticTitle, syntheticDescription(policy), now));
    }

    public String syntheticTitle(ThresholdPolicy policy) {
        return "Threshold: " + policy.count() + "+ critical events in " + policy.windowMin() + " minutes";
    }

    private String syntheticDescription(ThresholdPolicy policy) {
        return "Auto-generated by threshold rule after " + policy.count()
                + " critical events within " + policy.windowMin() + " minutes";
    }
}
